### ISSUE TITLE
Build error against PostgreSQL 17

### ISSUE THREAD

**Issue by devrimgunduz** [RekGRpth/pg_task#10]
Hi,

2.1.5 fails to build against PostgreSQL 17. Can you please take a look? Thanks! Devrim

> gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -fvisibility=hidden -I/usr/pgsql-17/include -I. -I./ -I/usr/pgsql-17/include/server -I/usr/pgsql-17/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2 -DWITH_GZFILEOP  -I/usr/include  -c -o dest.o dest.c
> In file included from dest.c:141:
> ./postgres.c: In function ‘PostgresSingleUserMain’:
> ./postgres.c:4194:9: error: implicit declaration of function ‘InitializeFastPathLocks’ [-Wimplicit-function-declaration]
>  4194 |         InitializeFastPathLocks();
>       |         ^~~~~~~~~~~~~~~~~~~~~~~
> ./postgres.c: In function ‘PostgresMain’:
> ./postgres.c:4337:17: error: ‘MyCancelKeyValid’ undeclared (first use in this function); did you mean ‘MyCancelKey’?
>  4337 |                 MyCancelKeyValid = true;
>       |                 ^~~~~~~~~~~~~~~~
>       |                 MyCancelKey
> ./postgres.c:4337:17: note: each undeclared identifier is reported only once for each function it appears in
> make[1]: *** [<builtin>: dest.o] Error 1
>

**Comment by RekGRpth** [comment]
Can you describe in more detail how you compiled? It compiles fine for me with version [17](https://github.com/RekGRpth/postgres.docker/actions/runs/11000907603/job/30558971535), and even with [18](https://github.com/RekGRpth/postgres.docker/actions/runs/11000907603/job/30558969809) too!

**Comment by RekGRpth** [comment]
If you compiled postgres 17 from source, try using the environment variable PG_BUILD_FROM_SOURCE to compile pg_task.

**Comment by RekGRpth** [comment]
fixed by https://github.com/RekGRpth/pg_task/commit/39dcc8ce1495698b3987d04759f40aab199a6173

**Comment by devrimgunduz** [comment]
Hi,

This patch did not fix the problem on my side even if I try with v17.0 and I think I found the problem. It is in the Makefile:

https://github.com/RekGRpth/pg_task/blob/c053e6be826de4eb5fb5347f1575c79d1f3479b3/Makefile#L30

This line assumes that related tag is created on github. That is why it works against v16 and etc, but not on 17.0. See below:
```
+ /usr/bin/make PG_CONFIG=/usr/pgsql-17/bin/pg_config PATH=/usr/pgsql-17/bin/:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin USE_PGXS=1 -j12
make[1]: Entering directory '/var/lib/pgsql/git/pgrpms/rpm/redhat/main/non-common/pg_task/main/pg_task_17-2.1.5-build/pg_task-2.1.5'
wget -O postgres.c "https://raw.githubusercontent.com/postgres/postgres/REL_17_0/src/backend/tcop/postgres.c" || wget -O postgres.c "https://raw.githubusercontent.com/postgres/postgres/master/src/backend/tcop/postgres.c"
0 files              100% [===========================================================================================================================================================================================>]      14     --.-KB/s
                          [Files: 0  Bytes: 14  [50 B/s] Redirects: 0  Todo: 0  Errors: 1                                                                                                                              ]
postgres.c           100% [===========================================================================================================================================================================================>]   40.29K    --.-KB/s
                          [Files: 1  Bytes: 40.29K [183.15KB/s] Redirects: 0  Todo: 0  Errors: 0                                                                                                                       ]
```

So basically it throws 404. If I replace ${REL} on that line 30 with REL_17_STABLE (17 is the variable there) it works.

Hope this helps.

Regards, Devrim

**Comment by RekGRpth** [comment]
try https://github.com/RekGRpth/pg_task/commit/d8dd38e0f5b33d1ff78a1f5ae0289ea12a03ad35

**Comment by devrimgunduz** [comment]
Thanks a lot! It worked!

Any chance you can release  a new version so that I can build the RPMs?

Thanks! Devrim

**Comment by RekGRpth** [comment]
> you can release a new version

done

**Comment by devrimgunduz** [comment]
Sorry for being too noisy but the version on PGXN was 2.1.5, so the new release should be higher than that one. Otherwise upgrade paths will be broken.

Regards, Devrim

**Comment by devrimgunduz** [comment]
Sorry, I saw the tag on github. All clear now. Thanks again!
